# Generated by Django 5.2.8 on 2025-11-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='state',
            field=models.CharField(choices=[('PENDING', '等待中'), ('PUBLISH', '已发布'), ('PROCESSING', '正在执行'), ('SLEEP', '休眠'), ('RETRY', '等待重试'), ('SKIP', '跳过'), ('TIMEOUT', '超时'), ('SUCCESS', '成功'), ('ERROR', '错误'), ('REVOKE', '撤销'), ('TERMINATE', '终止')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('PENDING', '等待中'), ('PROCESSING', '正在执行'), ('SLEEP', '休眠'), ('RETRY', '等待重试'), ('SKIP', '跳过'), ('TIMEOUT', '超时'), ('SUCCESS', '成功'), ('ERROR', '错误'), ('REVOKE', '撤销'), ('TERMINATE', '终止')], db_index=True, max_length=64),
        ),
    ]
