# Generated by Django 5.2.8 on 2025-11-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaflow', '0003_alter_task_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='root',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='seaflow.task'),
        ),
    ]
