# Generated by Django 5.2.8 on 2025-11-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaflow', '0004_alter_task_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='input_def',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='node',
            name='output_def',
            field=models.JSONField(default=dict),
        ),
    ]
